version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install -g serverless@2.4.0
      - cd brokerage && npm install
      - cd ../migration && npm install

  build:
    commands:
      - DB_HOST=$DB_HOST DB_PORT=$DB_PORT DB_USERNAME=$DB_USERNAME DB_PASSWORD=$DB_PASSWORD DB_DATABASE=$DB_DATABASE npm run migrate-up

  post_build:
    commands:
      - cd ../brokerage
      - sls deploy -v
